apiVersion: v1
kind: Pod
metadata:
  name: simple-web-pod
  labels:
    app: simple-web 
spec:
  containers:
  - name: simple-web-container
    image: pratul1999/simple-web:latest
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: simple-web-service
spec:
  selector:
    app: simple-web
  type: NodePort
  selector:
    app: simple-web
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
